const NAMESPACE = 'GENERAL';

export const GET_LOG_EVENTS = `${NAMESPACE}/GET_LOG_EVENTS`;
export const GET_LOG_EVENTS_OK = `${GET_LOG_EVENTS}_OK`;

export const GET_LOGS = `${NAMESPACE}/GET_LOGS`;
export const GET_LOGS_OK = `${GET_LOGS}_OK`;

export const LOG_EVENT_CHANGE = `${NAMESPACE}/LOG_EVENT_CHANGE`;
export const LOG_MASS_SELECT = `${NAMESPACE}/LOG_MASS_SELECT`;
export const LOG_SAVE_SETTING = `${NAMESPACE}/LOG_SAVE_SETTING`;
export const LOG_DELETE_SETTING = `${NAMESPACE}/LOG_DELETE_SETTING`;
export const LOG_CREATE_SETTINGS = `${NAMESPACE}/LOG_CREATE_SETTING`;
export const LOG_CREATE_SETTINGS_OK = `${LOG_CREATE_SETTINGS}_OK`;