const NAMESPACE = 'GENERAL';

const LOGS = {
    GET_LOG_EVENTS: `${NAMESPACE}/GET_LOG_EVENTS`,
    GET_LOG_EVENTS_OK: `${NAMESPACE}GET_LOG_EVENTS_OK`,

    GET_LOG_SETTINGS: `${NAMESPACE}/GET_LOG_SETTINGS`,
    GET_LOG_SETTINGS_OK: `${NAMESPACE}/GET_LOG_SETTINGS_OK`,

    EVENT_CHANGE: `${NAMESPACE}/LOG_EVENT_CHANGE`,
    MASS_SELECT: `${NAMESPACE}/LOG_MASS_SELECT`,
    SAVE_SETTING: `${NAMESPACE}/LOG_SAVE_SETTING`,
    DELETE_SETTING: `${NAMESPACE}/LOG_DELETE_SETTING`,
    CREATE_SETTING: `${NAMESPACE}/LOG_CREATE_SETTING`,
    CREATE_SETTING_OK: `${NAMESPACE}/LOG_CREATE_SETTING_OK`
};

export {LOGS}